const express = require("express");
const router = express.Router();
const pdfDownload = require("../pdf");
const excel = require("../excel");
const collegeController = require("../controllers/collegeController");
router.post("/registerCollege", collegeController.registerCollege);
router.get("/downloadPDF", pdfDownload.collegePdf);
router.get("/downloadExcel", excel.collegedownload);
router.get("/getCollegeCount", collegeController.getCollegeCount);
module.exports = router;
